### ISSUE TITLE
iOS Infinite Loading

### ISSUE THREAD

**Issue by KingRial** [PWA-POLICE/pwa-bugs#10]
Is there any working example to handle the [Infinite Loading](https://github.com/PWA-POLICE/pwa-bugs#problem-navigation-to-a-website-has-infinite-loading) on iOS ?

I am trying to follow the proposed solution but without success.

**Comment by NekR** [comment]
Hi. I may publish one soon. I'll let you know

**Comment by danielbayerlein** [comment]
@KingRial Have you found a solution?

**Comment by KingRial** [comment]
@danielbayerlein Unluckily, up to now on iOS 12+ I just admitted defeat when using PWA technology.
I hope iOS 13 will change the situation.

**Comment by lastmjs** [comment]
@kingrial I'm sorry for our loss, this is kind of tragic

**Comment by danielbayerlein** [comment]
@KingRial Looks like the problem has been fixed with iOS 13.

**Comment by danburzo** [comment]
I still have issues with SW-powered websites not loading on iOS 13. I experience it daily on mobile.twitter.com and dev.to, for example. So, while it feels like iOS 13 brought some improvements, it has not fixed the infinite loading problem.

**Comment by KingRial** [comment]
@danburzo I can confirm that iOS 13 has improved the situation but hasn't solved the main problem.
From the little I understood, I get the "inifinite loading" whenever I update my PWA and it exceeds the cache limit on iOS (which is 50Mb).

Usually it happens because each "service worker" has it's own life and it's own size.

For example, if you have a PWA of around 22Mb, and you install it and then update it for the first time, the problem doesn't occur (44Mb are lesser that the 50Mb limit)

But if you update the PWA a second time it seems you exceeds the cache limit because the first unused service worker wasn't cleaned by the OS (66Mb are bigger than 50Mb); in this case the OS kills the service worker's caches in a odd way and 90% of times nothing works until you clean the temporary files in the safari browser...
